/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all jobs */
        get: operations["ListJobs"];
        put?: never;
        /** Submit a new Job (AWU) */
        post: operations["SubmitJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user job details */
        get: operations["GetJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream job logs and status updates (SSE) */
        get: operations["StreamJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve a file directly from the job workspace */
        get: operations["ServeJobFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all workflows */
        get: operations["ListWorkflows"];
        put?: never;
        /** Create a new workflow definition */
        post: operations["CreateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow details and status */
        get: operations["GetWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a workflow */
        post: operations["RunWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a paused workflow */
        post: operations["ResumeWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat with the Agent */
        post: operations["AgentChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all conversations */
        get: operations["ListConversations"];
        put?: never;
        /** Create a new conversation */
        post: operations["CreateConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get conversation details */
        get: operations["GetConversation"];
        put?: never;
        post?: never;
        /** Delete a conversation */
        delete: operations["DeleteConversation"];
        options?: never;
        head?: never;
        /** Update conversation (e.g. title) */
        patch: operations["UpdateConversation"];
        trace?: never;
    };
    "/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a conversation */
        get: operations["ListMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current settings (secrets masked) */
        get: operations["GetSettings"];
        /** Update settings (encrypts secrets at rest) */
        put: operations["UpdateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test provider connection */
        post: operations["TestConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["ListProjects"];
        put?: never;
        /** Create a new project */
        post: operations["CreateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["GetProject"];
        put?: never;
        post?: never;
        /** Delete a project */
        delete: operations["DeleteProject"];
        options?: never;
        head?: never;
        /** Update project (name, description) */
        patch: operations["UpdateProject"];
        trace?: never;
    };
    "/v1/projects/{id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations in a project */
        get: operations["ListProjectConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List artifacts in a project */
        get: operations["ListProjectArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all artifacts */
        get: operations["ListArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/artifacts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifact details */
        get: operations["GetArtifact"];
        put?: never;
        post?: never;
        /** Delete an artifact */
        delete: operations["DeleteArtifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available models (from catalog) */
        get: operations["ListModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover models from Ollama and/or LiteLLM */
        post: operations["DiscoverModels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream conversation events including sub-agent activity (SSE) */
        get: operations["StreamConversationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all personas */
        get: operations["ListPersonas"];
        put?: never;
        /** Create a custom persona */
        post: operations["CreatePersona"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get persona details */
        get: operations["GetPersona"];
        put?: never;
        post?: never;
        /** Delete a persona */
        delete: operations["DeletePersona"];
        options?: never;
        head?: never;
        /** Update persona */
        patch: operations["UpdatePersona"];
        trace?: never;
    };
    "/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List loaded Synapse plugins */
        get: operations["ListPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all system capabilities (muscle + synapse) */
        get: operations["ListCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatRequest: {
            /** @example Run a python script that prints hello */
            message: string;
            /** @example llama3 */
            model?: string;
            /** @description Optional. If omitted, a new conversation is created automatically. */
            conversation_id?: string;
            /** @description Optional persona ID to use for this chat. Sets the agent personality and tool filter. */
            persona_id?: string;
        };
        ChatResponse: {
            response?: string;
            /** @description Chain of thought or reasoning trace */
            thought?: string;
            /** @description The conversation this message belongs to */
            conversation_id?: string;
            tool_call?: {
                name?: string;
                args?: Record<string, never>;
            };
            steps?: components["schemas"]["ReActStep"][];
        };
        ReActStep: {
            thought?: string;
            action?: string;
            action_input?: {
                [key: string]: unknown;
            };
            observation?: string;
            is_final_answer?: boolean;
            final_answer?: string;
        };
        JobRequest: {
            /** @example python:3.10-slim */
            image: string;
            /**
             * @example [
             *       "python",
             *       "-c",
             *       "print('Hello World')"
             *     ]
             */
            command: string[];
            env?: {
                [key: string]: string;
            };
            resources?: components["schemas"]["Resources"];
        };
        JobResponse: {
            id?: string;
            status?: string;
        };
        Job: {
            id?: string;
            status?: string;
            result?: string;
            error?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Resources: {
            cpu?: number;
            memory_mb?: number;
        };
        Error: {
            error?: string;
        };
        Conversation: {
            id?: string;
            title?: string;
            /** @description Optional project this conversation belongs to */
            project_id?: string;
            /** @description Optional persona used in this conversation */
            persona_id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Message: {
            id?: string;
            conversation_id?: string;
            /** @enum {string} */
            role?: "user" | "assistant" | "system" | "tool";
            content?: string;
            thought?: string;
            steps?: components["schemas"]["ReActStep"][];
            tool_call?: {
                name?: string;
                args?: Record<string, never>;
            };
            /** Format: date-time */
            created_at?: string;
        };
        ProviderConfig: {
            /**
             * @description 'local' for Ollama/ComfyUI, 'remote' for OpenAI-compatible API
             * @enum {string}
             */
            mode?: "local" | "remote";
            /** @example http://localhost:11434/v1 */
            local_url?: string;
            /** @example https://api.openai.com/v1 */
            remote_url?: string;
            /** @description Masked on read (****xxxx), plaintext on write. Empty string keeps existing. */
            api_key?: string;
            /** @example gemma3:12b */
            default_model?: string;
        };
        AppConfig: {
            providers?: {
                llm?: components["schemas"]["ProviderConfig"];
                image?: components["schemas"]["ProviderConfig"];
            };
        };
        ConnectionTestResult: {
            provider?: string;
            mode?: string;
            url?: string;
            model?: string;
            /** @enum {string} */
            status?: "ok" | "error";
            message?: string;
        };
        Project: {
            id?: string;
            name?: string;
            description?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Artifact: {
            id?: string;
            project_id?: string;
            job_id?: string;
            conversation_id?: string;
            /** @enum {string} */
            type?: "image" | "text" | "document" | "audio" | "video" | "other";
            name?: string;
            file_path?: string;
            mime_type?: string;
            /** Format: int64 */
            size_bytes?: number;
            prompt?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Persona: {
            id?: string;
            name?: string;
            description?: string;
            system_prompt?: string;
            /** @description Lucide icon name */
            icon?: string;
            /** @description Tailwind color token (e.g. blue, emerald, violet) */
            color?: string;
            /** @description Tool names this persona can use. Empty means all tools. */
            allowed_tools?: string[];
            /** @description Model to use for this persona. Empty means use system default. */
            model_override?: string;
            is_builtin?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ModelSpec: {
            /** @example qwen2.5:3b */
            id?: string;
            /** @example Qwen 2.5 3B */
            name?: string;
            /** @example ollama */
            provider?: string;
            /** @enum {string} */
            role?: "general" | "code" | "creative" | "fast";
            /** @example 3B */
            size?: string;
            base_url?: string;
            is_local?: boolean;
        };
        SubAgentEvent: {
            sub_agent_id?: string;
            parent_id?: string;
            conversation_id?: string;
            persona_name?: string;
            persona_color?: string;
            persona_icon?: string;
            model_id?: string;
            /** @enum {string} */
            status?: "pending" | "running" | "done" | "failed";
            thought?: string;
            result?: string;
            error?: string;
        };
        Plugin: {
            /** @example prompt-enhancer */
            name?: string;
            /** @example 1.0.0 */
            version?: string;
            /** @example Enhances image prompts with quality keywords */
            description?: string;
            /** @example enhance_prompt */
            tool_name?: string;
            /** @example synapse */
            runtime?: string;
        };
        PluginListResponse: {
            plugins?: components["schemas"]["Plugin"][];
            count?: number;
        };
        Capability: {
            /** @example image.generate */
            capability?: string;
            /** @enum {string} */
            runtime?: "muscle" | "synapse";
            description?: string;
        };
        CapabilityStats: {
            muscle?: number;
            synapse?: number;
            total?: number;
        };
        CapabilityListResponse: {
            capabilities?: components["schemas"]["Capability"][];
            stats?: components["schemas"]["CapabilityStats"];
        };
        Workflow: {
            id?: string;
            project_id?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            status?: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
            state?: {
                [key: string]: unknown;
            };
            steps?: components["schemas"]["WorkflowStep"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            error?: string;
        };
        WorkflowStep: {
            id?: string;
            persona_id?: string;
            prompt?: string;
            tools?: string[];
            depends_on?: string[];
            /** @enum {string} */
            status?: "pending" | "running" | "done" | "failed" | "skipped";
            result?: {
                output?: string;
                metadata?: Record<string, never>;
            };
            interrupt?: {
                before?: boolean;
                after?: boolean;
                message?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    SubmitJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Job created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Invalid job specification */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job Details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    StreamJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServeJobFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of workflows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"][];
                };
            };
        };
    };
    CreateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    project_id?: string;
                    name: string;
                    description?: string;
                    steps: components["schemas"]["WorkflowStep"][];
                };
            };
        };
        responses: {
            /** @description Workflow created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RunWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        status?: string;
                    };
                };
            };
            /** @description Workflow not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResumeWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    state_updates?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Workflow resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    AgentChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Agent Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ListConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    CreateConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example New Chat */
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    GetConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    DeleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Updated conversation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    ListMessages: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
        };
    };
    GetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current application settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    UpdateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfig"];
            };
        };
        responses: {
            /** @description Updated settings (secrets masked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    TestConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    provider: "llm" | "image";
                };
            };
        };
        responses: {
            /** @description Connection test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
        };
    };
    ListProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    CreateProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Campaign Q4 */
                    name: string;
                    /** @example Marketing campaign assets */
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    GetProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    DeleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                };
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ListProjectConversations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations in the project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    ListProjectArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of artifacts in the project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
        };
    };
    ListArtifacts: {
        parameters: {
            query?: {
                /** @description Filter by artifact type */
                type?: "image" | "text" | "document" | "audio" | "video" | "other";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of artifacts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"][];
                };
            };
        };
    };
    GetArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            /** @description Artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    DeleteArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSpec"][];
                };
            };
        };
    };
    DiscoverModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @example http://localhost:11434 */
                    ollama_url?: string;
                    /** @example http://localhost:4000 */
                    litellm_url?: string;
                    litellm_api_key?: string;
                };
            };
        };
        responses: {
            /** @description Discovered models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSpec"][];
                };
            };
        };
    };
    StreamConversationEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    ListPersonas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of personas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"][];
                };
            };
        };
    };
    CreatePersona: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Analyst */
                    name: string;
                    /** @example Data analysis specialist */
                    description?: string;
                    /** @example You are a data analyst... */
                    system_prompt: string;
                    /** @example bar-chart */
                    icon?: string;
                    /** @example cyan */
                    color?: string;
                    allowed_tools?: string[];
                    /** @description Override model for this persona (e.g. qwen2.5-coder:3b) */
                    model_override?: string;
                };
            };
        };
        responses: {
            /** @description Persona created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
        };
    };
    GetPersona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persona details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
            /** @description Persona not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    DeletePersona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdatePersona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    description?: string;
                    system_prompt?: string;
                    icon?: string;
                    color?: string;
                    allowed_tools?: string[];
                    model_override?: string;
                };
            };
        };
        responses: {
            /** @description Updated persona */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
            /** @description Persona not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ListPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of loaded Wasm plugins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginListResponse"];
                };
            };
        };
    };
    ListCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability map with stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityListResponse"];
                };
            };
        };
    };
}
