//go:build go1.22

// Package kernel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package kernel

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	Message string  `json:"message"`
	Model   *string `json:"model,omitempty"`
}

// ChatResponse defines model for ChatResponse.
type ChatResponse struct {
	Response *string      `json:"response,omitempty"`
	Steps    *[]ReActStep `json:"steps,omitempty"`

	// Thought Chain of thought or reasoning trace
	Thought  *string `json:"thought,omitempty"`
	ToolCall *struct {
		Args *map[string]interface{} `json:"args,omitempty"`
		Name *string                 `json:"name,omitempty"`
	} `json:"tool_call,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error *string `json:"error,omitempty"`
}

// Job defines model for Job.
type Job struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Error     *string    `json:"error,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Result    *string    `json:"result,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// JobRequest defines model for JobRequest.
type JobRequest struct {
	Command   []string           `json:"command"`
	Env       *map[string]string `json:"env,omitempty"`
	Image     string             `json:"image"`
	Resources *Resources         `json:"resources,omitempty"`
}

// JobResponse defines model for JobResponse.
type JobResponse struct {
	Id     *string `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
}

// ReActStep defines model for ReActStep.
type ReActStep struct {
	Action        *string                 `json:"action,omitempty"`
	ActionInput   *map[string]interface{} `json:"action_input,omitempty"`
	FinalAnswer   *string                 `json:"final_answer,omitempty"`
	IsFinalAnswer *bool                   `json:"is_final_answer,omitempty"`
	Observation   *string                 `json:"observation,omitempty"`
	Thought       *string                 `json:"thought,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	Cpu      *float32 `json:"cpu,omitempty"`
	MemoryMb *int     `json:"memory_mb,omitempty"`
}

// AgentChatJSONRequestBody defines body for AgentChat for application/json ContentType.
type AgentChatJSONRequestBody = ChatRequest

// SubmitJobJSONRequestBody defines body for SubmitJob for application/json ContentType.
type SubmitJobJSONRequestBody = JobRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chat with the Agent
	// (POST /v1/agent/chat)
	AgentChat(w http.ResponseWriter, r *http.Request)
	// List all jobs
	// (GET /v1/jobs)
	ListJobs(w http.ResponseWriter, r *http.Request)
	// Submit a new Job (AWU)
	// (POST /v1/jobs)
	SubmitJob(w http.ResponseWriter, r *http.Request)
	// Get user job details
	// (GET /v1/jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id string)
	// Serve a file directly from the job workspace
	// (GET /v1/jobs/{id}/files/{filename})
	ServeJobFile(w http.ResponseWriter, r *http.Request, id string, filename string)
	// Stream job logs and status updates (SSE)
	// (GET /v1/jobs/{id}/stream)
	StreamJob(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AgentChat operation middleware
func (siw *ServerInterfaceWrapper) AgentChat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AgentChat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJobs operation middleware
func (siw *ServerInterfaceWrapper) ListJobs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJobs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitJob operation middleware
func (siw *ServerInterfaceWrapper) SubmitJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeJobFile operation middleware
func (siw *ServerInterfaceWrapper) ServeJobFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", r.PathValue("filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "filename", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeJobFile(w, r, id, filename)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamJob operation middleware
func (siw *ServerInterfaceWrapper) StreamJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/v1/agent/chat", wrapper.AgentChat)
	m.HandleFunc("GET "+options.BaseURL+"/v1/jobs", wrapper.ListJobs)
	m.HandleFunc("POST "+options.BaseURL+"/v1/jobs", wrapper.SubmitJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/jobs/{id}", wrapper.GetJob)
	m.HandleFunc("GET "+options.BaseURL+"/v1/jobs/{id}/files/{filename}", wrapper.ServeJobFile)
	m.HandleFunc("GET "+options.BaseURL+"/v1/jobs/{id}/stream", wrapper.StreamJob)

	return m
}

type AgentChatRequestObject struct {
	Body *AgentChatJSONRequestBody
}

type AgentChatResponseObject interface {
	VisitAgentChatResponse(w http.ResponseWriter) error
}

type AgentChat200JSONResponse ChatResponse

func (response AgentChat200JSONResponse) VisitAgentChatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AgentChat500JSONResponse Error

func (response AgentChat500JSONResponse) VisitAgentChatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListJobsRequestObject struct {
}

type ListJobsResponseObject interface {
	VisitListJobsResponse(w http.ResponseWriter) error
}

type ListJobs200JSONResponse []Job

func (response ListJobs200JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListJobs500JSONResponse Error

func (response ListJobs500JSONResponse) VisitListJobsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SubmitJobRequestObject struct {
	Body *SubmitJobJSONRequestBody
}

type SubmitJobResponseObject interface {
	VisitSubmitJobResponse(w http.ResponseWriter) error
}

type SubmitJob201JSONResponse JobResponse

func (response SubmitJob201JSONResponse) VisitSubmitJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SubmitJob400JSONResponse Error

func (response SubmitJob400JSONResponse) VisitSubmitJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SubmitJob500JSONResponse Error

func (response SubmitJob500JSONResponse) VisitSubmitJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetJobRequestObject struct {
	Id string `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse Job

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJob404JSONResponse Error

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ServeJobFileRequestObject struct {
	Id       string `json:"id"`
	Filename string `json:"filename"`
}

type ServeJobFileResponseObject interface {
	VisitServeJobFileResponse(w http.ResponseWriter) error
}

type ServeJobFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ServeJobFile200ApplicationoctetStreamResponse) VisitServeJobFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ServeJobFile404Response struct {
}

func (response ServeJobFile404Response) VisitServeJobFileResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ServeJobFile500Response struct {
}

func (response ServeJobFile500Response) VisitServeJobFileResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type StreamJobRequestObject struct {
	Id string `json:"id"`
}

type StreamJobResponseObject interface {
	VisitStreamJobResponse(w http.ResponseWriter) error
}

type StreamJob200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response StreamJob200TexteventStreamResponse) VisitStreamJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type StreamJob404Response struct {
}

func (response StreamJob404Response) VisitStreamJobResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Chat with the Agent
	// (POST /v1/agent/chat)
	AgentChat(ctx context.Context, request AgentChatRequestObject) (AgentChatResponseObject, error)
	// List all jobs
	// (GET /v1/jobs)
	ListJobs(ctx context.Context, request ListJobsRequestObject) (ListJobsResponseObject, error)
	// Submit a new Job (AWU)
	// (POST /v1/jobs)
	SubmitJob(ctx context.Context, request SubmitJobRequestObject) (SubmitJobResponseObject, error)
	// Get user job details
	// (GET /v1/jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)
	// Serve a file directly from the job workspace
	// (GET /v1/jobs/{id}/files/{filename})
	ServeJobFile(ctx context.Context, request ServeJobFileRequestObject) (ServeJobFileResponseObject, error)
	// Stream job logs and status updates (SSE)
	// (GET /v1/jobs/{id}/stream)
	StreamJob(ctx context.Context, request StreamJobRequestObject) (StreamJobResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AgentChat operation middleware
func (sh *strictHandler) AgentChat(w http.ResponseWriter, r *http.Request) {
	var request AgentChatRequestObject

	var body AgentChatJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AgentChat(ctx, request.(AgentChatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgentChat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AgentChatResponseObject); ok {
		if err := validResponse.VisitAgentChatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListJobs operation middleware
func (sh *strictHandler) ListJobs(w http.ResponseWriter, r *http.Request) {
	var request ListJobsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListJobs(ctx, request.(ListJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListJobs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListJobsResponseObject); ok {
		if err := validResponse.VisitListJobsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SubmitJob operation middleware
func (sh *strictHandler) SubmitJob(w http.ResponseWriter, r *http.Request) {
	var request SubmitJobRequestObject

	var body SubmitJobJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubmitJob(ctx, request.(SubmitJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubmitJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubmitJobResponseObject); ok {
		if err := validResponse.VisitSubmitJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id string) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ServeJobFile operation middleware
func (sh *strictHandler) ServeJobFile(w http.ResponseWriter, r *http.Request, id string, filename string) {
	var request ServeJobFileRequestObject

	request.Id = id
	request.Filename = filename

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ServeJobFile(ctx, request.(ServeJobFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ServeJobFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ServeJobFileResponseObject); ok {
		if err := validResponse.VisitServeJobFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StreamJob operation middleware
func (sh *strictHandler) StreamJob(w http.ResponseWriter, r *http.Request, id string) {
	var request StreamJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StreamJob(ctx, request.(StreamJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StreamJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StreamJobResponseObject); ok {
		if err := validResponse.VisitStreamJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX247bNhN+FYL/DyQBtLa3SW98t03S1NsiDdYNchEvDFoaW9zyFHLkjWH43Ysh5aOk",
	"xm12i72yLI44M9+BhzXPrXbWgMHAh2se8hK0iI+vS4E38KWCgPTXeevAo4Q4qCEEsQB6hK9COwV8yG8q",
	"wwRzKyytYSH30iHDUiBzXhoMrASlLM84rhyFB/TSLPgm49oWoI7nUkpo8bIZvMm4hy+V9FDw4eddHbe7",
	"QDu7gxxp1tRAcNYEaHbgD0YaBQUEF6Mkgo4P//cw50P+v/4er34NVv8GrnIcIzj6tJ5LeC9W8X9pq0UZ",
	"ISwggSKt4UMqTxpm56yOYNYzDyJYI82CoRc5tGGF1qppLpRqtiT8Ihy0s0fCCN3W56YB2qYFxrfeW99M",
	"BtvX35w049d21pwg9yAQiqmI2Myt1/TEC4FwgVK3Nt+VNOOyaH3tIVQKOzgWWIXzO+j0Qm61FqY40u9n",
	"nmzAM36R84xHBzx/9gs5gH2yXhXPXpBod/pq8nyiIzDLyHFRSBKQUB+Oiuj6ft+C1A3DphqHL3uXg4ug",
	"pG6D3EOwlc/hDBdsA09NmjJnO6BuuwDu8moHuf+Iwb1Jm77JkyVbUqShqTSuwm740VfQknIujVBTYcI9",
	"dIg2TDtiZtYqEIaC7CyAX4rOEg8WmLNgOKDzRMeuOpjEVHoGPq7OoK1fTfXsYFQahAUNt6wh1JiZ2+aK",
	"d/VhxObWMyyBiUrB72P2K3gDKmNCKXtP616oZloi0uOdnQUmTMECehCaXim7CD1SqcQo4KNZ2NWHEc/4",
	"EnxI+Qa9y94gQujACCf5kL/sDXq0qziBZWy6v7zsiwUY7OdlWomcTSYnaCLqo4JqpxjaUXjSNgT8yRar",
	"5H+DYJI8nFMyj1/170IiLPnjW+453G03xwYidSUjRnvEsn8YDB44de29mPuENmqd7SMy/uMDZk/bS0va",
	"kUHwRihG8gfPoA7MeKi0Fn6V9lBk9xLLqKlYaIwgVkk+lHwBLXT+JgNeU8B34nrW+YC2v8aK3myYaqLz",
	"QCz8KaEcCxNK7Sprt8g4WpeafRyLHOzBZznk8mEzdxvk2s5YfZphocpzCGFeKRW37Vf/DYlLoWRB/LDg",
	"IJfzOsGTklHSBxPMwD0jzJ5fffr44siv/bUsNp2mfQe1upzwQgOCD3z4ed3CxugNp02IjjgCS749AdNB",
	"4lQ32UHrp/vn7SOuunFRaNfSG0AhVUjyefX45FFOY5HNbWWKE9LeAbIqgI/aKraFnVLWn0sFob+mH4K6",
	"m8Mx6ePazn6WCppMfj9lWesk27oekX2bI+BFOqocc7K72sykIVCbd9oGI3+UwKhmtk22l8JxIMF4yN3O",
	"7v/CnjTERMpbSA85qhWbe6vj5kr831v/Z3B0MW0qYN95O+9x+KnZF+Er9mEJpp25/U0pxgxZunFMTCFQ",
	"DNl6Ul9BJnzIJvzm4/v3o/fvJnwzMRNTf6Hs4iBcSQMp+LXVTippFr1eL35xjize0pz1cbhTEn/n5sRC",
	"5JKO0vXpmlpglaObd2DPx+O3tChvNn8FAAD//zzaJpUcEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
