openapi: 3.0.3
info:
  title: auleOS Kernel API
  version: 0.1.0
  description: API for the auleOS Kernel, allowing submitting jobs and streaming logs.

paths:
  /v1/jobs:
    post:
      summary: Submit a new Job (AWU)
      operationId: SubmitJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobRequest'
      responses:
        '201':
          description: Job created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '400':
          description: Invalid job specification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List all jobs
      operationId: ListJobs
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/jobs/{id}:
    get:
      summary: Get user job details
      operationId: GetJob
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Job ID
      responses:
        '200':
          description: Job Details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/jobs/{id}/stream:
    get:
      summary: Stream job logs and status updates (SSE)
      operationId: StreamJob
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Job ID
      responses:
        '200':
          description: Event stream
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  event: status
                  data: {"status": "RUNNING"}

                  event: log
                  data: {"line": "Compiling..."}
        '404':
          description: Job not found

  /v1/jobs/{id}/files/{filename}:
    get:
      summary: Serve a file directly from the job workspace
      operationId: ServeJobFile
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The file content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: File not found
        '500':
          description: Internal server error

  /v1/agent/chat:
    post:
      summary: Chat with the Agent
      operationId: AgentChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Agent Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ChatRequest:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          example: "Run a python script that prints hello"
        model:
          type: string
          example: "llama3"

    ChatResponse:
      type: object
      properties:
        response:
          type: string
        thought:
          type: string
          description: "Chain of thought or reasoning trace"
        tool_call:
          type: object
          properties:
            name:
              type: string
            args:
              type: object
        steps:
          type: array
          items:
            $ref: '#/components/schemas/ReActStep'

    ReActStep:
      type: object
      properties:
        thought:
          type: string
        action:
          type: string
        action_input:
          type: object
          additionalProperties: true
        observation:
          type: string
        is_final_answer:
          type: boolean
        final_answer:
          type: string

    JobRequest:
      type: object
      required:
      - image
      - command
      properties:
        image:
          type: string
          example: "python:3.10-slim"
        command:
          type: array
          items:
            type: string
          example: [ "python", "-c", "print('Hello World')" ]
        env:
          type: object
          additionalProperties:
            type: string
        resources:
          $ref: '#/components/schemas/Resources'

    JobResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string

    Job:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        result:
          type: string
        error:
          type: string
        created_at:
          type: string
          format: date-time

    Resources:
      type: object
      properties:
        cpu:
          type: number
        memory_mb:
          type: integer

    Error:
      type: object
      properties:
        error:
          type: string
